version: '3'

services: 
  api-provider-service:
    build:
      context: .
      dockerfile: dockerfile-api-provider
    container_name: api-provider-service
    ports: 
      - "${API_PROVIDER_PORT}:${API_PROVIDER_PORT}"
    volumes:
      - node_modules:/usr/app/node_modules
      - ./api-provider:/usr/app
    env_file:
      - .env
    restart: always
    networks:
      - whatsapp-web-network

volumes:
  node_modules:

networks:
  whatsapp-web-network:
    external: true